spring.application.name=turnos-service
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

catalogo.url=${CATALOGO_SERVICE_URL}
catalogo.client-id=${SERVICE_CLIENT_ID}
catalogo.client-secret=${SERVICE_CLIENT_SECRET}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true